- name: Create a volume
  docker_volume:
    name: portainer_data

- name: Create a container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:latest
    restart: true
    restart_policy: always
    
    devices:
     - "/dev/sda:/dev/xvda:rwm"
     
    ports:
      - "18000:8000"
      - "9443:9443" 
     
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
