# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_hosts = <<-SCRIPT
echo '192.168.56.21 swarm1'>> /etc/hosts
echo '192.168.56.22 swarm2'>> /etc/hosts
echo '192.168.56.23 swarm3'>> /etc/hosts
echo '192.168.56.24 swarm4'>> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|

  numNodes = 4
  ipAddrPrefix1 = "192.168.56.2"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
 end

 1.upto(numNodes) do |num|
  nodeName = ("swarm" + num.to_s).to_sym
  config.vm.define nodeName do |node|
    node.vm.host_name = nodeName
    node.vm.box = "ubuntu/focal64"
    node.vm.network :private_network, ip: ipAddrPrefix1 + num.to_s
    node.vm.provider "virtualbox" do |v|
       v.name = "SwarmNode" + num.to_s
      end
       node.vm.provision "shell", inline: $script_hosts
       node.vm.provision "shell", path: "scripts/install_docker.sh"
       node.vm.provision "shell", path: "scripts/install_opencti.sh"
       node.vm.provision "shell", path: "scripts/install_connector.sh"
       node.vm.provision "shell", path: "scripts/install_portainer.sh"
      
  end


  end
end