# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|


  config.vm.define "CTI-testt" do |machine|
	config.vm.network "public_network",
    use_dhcp_assigned_default_route: true
    machine.vm.hostname = "CTI-testt"
	machine.vm.box = "ubuntu/focal64"
    machine.vm.network :private_network, ip: "192.168.56.81"
    #machine.vm.network :private_network, ip: "10.33.4.3"

	machine.vm.synced_folder "./files", "/vagrant_files"
	machine.vm.synced_folder "./logs", "/home/vagrant/logs"
    machine.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--name", "CTI-testt"]
      v.customize ["modifyvm", :id, "--groups", "/OpenCTI_test"]
      v.customize ["modifyvm", :id, "--cpus", "1"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    end
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    #sed = chercher/remplacer
      sleep 3
      service sshd restart
    SHELL

    machine.vm.provision "shell", path: "scripts/install_docker.sh"
    machine.vm.provision "shell", path: "scripts/install_opencti.sh"
    machine.vm.provision "shell", path: "scripts/install_portainer.sh"
  end
end