# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "worker1" do |machine|
	machine.vm.hostname = "worker1"
	machine.vm.box = "ubuntu/focal64"
	machine.vm.network :private_network, ip: "192.168.99.101"
	machine.vm.synced_folder "./files", "/vagrant_files"
	machine.vm.synced_folder "./logs", "/home/vagrant/logs"
    
	machine.vm.provider :virtualbox do |v|
	  v.customize ["modifyvm", :id, "--name", "worker1"]
          v.customize ["modifyvm", :id, "--groups", "/swarm_test"]
          v.customize ["modifyvm", :id, "--cpus", "1"]
          v.customize ["modifyvm", :id, "--memory", 2048]
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
          v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
	end
	
        machine.vm.provision "shell", path: "scripts/install_sys.sh"
        
  end

  config.vm.provision "shell", inline: <<-SHELL
	sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config    #sed = chercher/remplacer
	sleep 3
	service sshd restart
  SHELL

  config.vm.provision "shell", run: "always", inline: "echo 'vagrant:dab123' | chpasswd"
      
end