Vagrant.configure("2") do |config|

  numMaster = 1
  ipAddrPrefix1 = "192.168.56.3"
  
  config.vm.network "public_network",
  use_dhcp_assigned_default_route: true

 1.upto(numMaster) do |num|
  nodeName = ("srv-deploiement").to_sym
  config.vm.define nodeName do |node|
    node.vm.host_name = nodeName
    node.vm.box = "ubuntu/focal64"
    node.vm.network :private_network, ip: ipAddrPrefix1 + num.to_s
    node.vm.provider "virtualbox" do |vb|
      vb.name = "srv-deploiement"
      vb.memory = 8192
    end
       node.vm.provision "shell", path: "scripts/init_env_v2.sh"
       node.vm.provision "shell", path: "scripts/init_ansible.sh" # A FINIR URGENT
      end
    end
    
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
    
    end

end
